require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/art", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Art. As you add validations to Art, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Art.create! valid_attributes
      get art_index_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      art = Art.create! valid_attributes
      get art_url(art)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_art_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      art = Art.create! valid_attributes
      get edit_art_url(art)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Art" do
        expect {
          post art_index_url, params: { art: valid_attributes }
        }.to change(Art, :count).by(1)
      end

      it "redirects to the created art" do
        post art_index_url, params: { art: valid_attributes }
        expect(response).to redirect_to(art_url(Art.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Art" do
        expect {
          post art_index_url, params: { art: invalid_attributes }
        }.to change(Art, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post art_index_url, params: { art: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested art" do
        art = Art.create! valid_attributes
        patch art_url(art), params: { art: new_attributes }
        art.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the art" do
        art = Art.create! valid_attributes
        patch art_url(art), params: { art: new_attributes }
        art.reload
        expect(response).to redirect_to(art_url(art))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        art = Art.create! valid_attributes
        patch art_url(art), params: { art: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested art" do
      art = Art.create! valid_attributes
      expect {
        delete art_url(art)
      }.to change(Art, :count).by(-1)
    end

    it "redirects to the art list" do
      art = Art.create! valid_attributes
      delete art_url(art)
      expect(response).to redirect_to(art_index_url)
    end
  end
end
